site_name: Orleans
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # --- MODE CLAIR ---
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Passer au mode sombre

    # --- MODE SOMBRE ---
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Passer au mode clair

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji

extra_css:
  - overrides.css

plugins: 
  - drawio

extra:
  css:
    - overrides.css
